### ISSUE TITLE
Setting dual dimensions for high resolution image and thumb image differently.

### ISSUE THREAD

**Issue by aligajani** [stylehatch/photoset-grid#63]
This is an interesting one. Currently, Photoset-Grid supports a single dimension data attributes (width and height) to render how the high resolution photos will be shown in the lightbox. This is tied to how the plugin renders the thumbs too. 

Now if the thumb and high resolution photo are in the same dimensions, it works fine. But this affects the entire grid if one photo has a weird aspect ratio. What if we want the thumbs to be of a fixed set dimensions (and this will be generated using Cloudinary's image transform API) . 

This will make the Photoset much more aligned with other photos since they will have the same thumb dimensions, but the Photoset-Grid plugin creates issues since changing the dimension on the image tag effects how the high resolution image is rendered. 

How do I resolve this. I want to be able to set dual dimensions so the plugin knows that these dimensions  are reserved for rendering the thumb impression and should not be fed of from the original aspect ratio of the high resolution image.

**Comment by jonathanmoore** [comment]
I think this is a situation and use case that goes well beyond what the photoset-grid plugin was intended.  By design it initially loads a smaller version of the image and if it's upscaled or stretched out it loads the higher resolution image.  The assumption that both images will be the same dimension is at the core of how the plugin works.  I think for what you're trying to accomplish a more custom solution might be necessary.
